name: postman-test

on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16','18']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g newman
      - run: run newman postman_tests\Books.postman_collection.json -e postman_tests\test.postman_environment.json
